# Generated by Django 3.2.15 on 2022-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your task', max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Describe the task', max_length=1500, verbose_name='description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is the task completed?')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
