# Generated by Django 3.2.15 on 2022-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_stage',
            field=models.CharField(choices=[('NW', 'New'), ('QU', 'Que'), ('PR', 'Progress'), ('RE', 'Review'), ('CO', 'Completed')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Hide the task so only the owner and the assignee can view it', verbose_name='private'),
        ),
    ]
