# Generated by Django 3.2.15 on 2022-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220927_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_stage',
            field=models.CharField(choices=[('NW', 'New'), ('QU', 'In Que'), ('PR', 'In Progress'), ('RE', 'Under Review'), ('CO', 'Completed')], default='NW', max_length=2),
        ),
    ]
