# Generated by Django 3.2.15 on 2022-09-27 13:29

from django.db import migrations, models
import django.db.models.deletion
import tasker.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_task_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=tasker.tasks.models.task_directory_path, verbose_name='Supporting file')),
                ('comment', models.TextField(blank=True, help_text='Add a comment', null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
