# Generated by Django 3.2.15 on 2022-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_update_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='time_spent',
            field=models.FloatField(blank=True, null=True, verbose_name='Time spent (Hours)'),
        ),
    ]
